### PR TITLE
fix #297

### LINKED ISSUE #297: harbor_replication with no speed produced an invalid new value for .speed
**Describe the bug**
harbor_replication with no speed : registry.terraform.io/goharbor/harbor" produced an invalid new value for .speed: was cty.NumberIntVal(0), but now null

**To Reproduce**
create a harbor_replication with no speed defined.

**Expected behavior**
Can create harbor_replication with no speed

### PR DESCRIPTION
**Pull request by flbla**

### CODE REVIEW

**Review by Vad1mo — APPROVED** [review]

File: provider/resource_replication.go [hunk 1]
```diff
@@ -96,7 +96,6 @@ func resourceReplication() *schema.Resource {
 			"speed": {
 				Type:     schema.TypeInt,
 				Optional: true,
-				Default:  0,
```
Comment (Vad1mo) [inline provider/resource_replication.go:99]: In the UI the default value is **-1**, should it also be here as well as default?
